name = "vikipedia"
pages_build_output_dir = "./dist"
compatibility_date = "2026-07-14"

[[d1_databases]]
binding = "VIKIPEDIA_DB"
database_name = "vikipedia"
database_id = "bdd320b2-008c-4ef9-a6fe-e2ba2df6570e"

[vars]
VGAMES_URL = "https://viota-worker.theonenonlyvj.workers.dev"
